### ISSUE TITLE
Install kodo-python

### ISSUE THREAD

**Issue by lxkaka** [steinwurf/kodo-python#35]
I am installing kodo-python on Ubuntu 14.04. As before it worked, but now it always show the problem:
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/kodo/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-elYkaT-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/kodo
Storing debug log for failure in /home/prakt/.pip/pip.log
How should I reslove this problem?

**Comment by petya2164** [comment]
@lxkaka Can you describe your installation steps in detail?
I guess you see this problem, because you don't have a valid Steinwurf license. I see that you just applied for it.

**Comment by lxkaka** [comment]
@petya2164  I appreciate your reply. I install kodo with command 'sudo pip install kodo' . At first I use my friend's account to install it, as before it woked.

**Comment by petya2164** [comment]
@lxkaka We granted you a license now. You can accept the invitation on github.
If you still have problems, then I recommend that you try to build from source (without pip):
https://github.com/steinwurf/kodo-python#building-from-source
Then you might get a nicer error message ;)

**Comment by lxkaka** [comment]
@petya2164  sorry, I can not see any invitation.

**Comment by petya2164** [comment]
@lxkaka "Invitations are sent via email and can be accepted at https://github.com/steinwurf"
Check the email address that you registered on github.

**Comment by petya2164** [comment]
@lxkaka Did you reach a solution?

**Comment by lxkaka** [comment]
@petya2164 Thank you very much for ask. The account issue is resloved, but when the complie reach 104/107 shows another error : 
  >::too_many_keywords assertion;
    
                                    ^
    
    g++: internal compiler error: Killed (program cc1plus)
    
    Please submit a full bug report,
    
    with preprocessed source if appropriate.
    
    See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
    
    
    
    Waf: Leaving directory `/tmp/pip-build-e_PyOs/kodo/kodo-python/build/cxx_default_x64'
    
    Build failed
    
     -> task in 'kodo-python' failed (exit status 4):
    
    	{task 140658391516368: cxx kodo.cpp -> kodo.cpp.1.o}

what is this kind of problem ?  In my finished Install has not this problem.

**Comment by petya2164** [comment]
@lxkaka This usually happens when your machine runs out of RAM. We recommend at least 4 GB RAM.
Try to close all other programs or just reboot the computer. You can also increase the size of your swap file.

**Comment by maxlio** [comment]
I faced the same problem in step [108/109] , I increased my Ubuntu14.04 virtual machine RAM to 4GB and swap up to 5GB but it's still the setup hanging for a long time without any response.

**Comment by mortenvp** [comment]
Hi @maxlio yeah the compilation eats quite a bit of memory. Do you have an option of not using the virtual machine to compile the binaries?

**Comment by petya2164** [comment]
@maxlio Actually, we have an Ubuntu VM with the same specs, and the compilation works fine on that (compilation time is around 5-8 minutes). Maybe your compiler/waf is trying to run 2 or more jobs at the same time, because the VM has access to multiple CPU cores. This could easily double/triple your RAM usage.
Can you try to configure your VM to use a single CPU?
Alternatively, you can try to force a single job with the "-j" option:
`python waf build -j 1`

**Comment by petya2164** [comment]
FYI, we added a new section in the project's readme about the compilation issues:
https://github.com/steinwurf/kodo-python#compilation-issues
The library was also restructured  to make the compilation faster in general.

**Comment by maxlio** [comment]
thanks! , it worked fine. 
I tried to install it also on my native machine (windows 8 ) using git bash. unfortunately , an error appears in waf configuration process as shown in the snap below ,
![test](https://cloud.githubusercontent.com/assets/5679145/7357852/2a872408-ed3a-11e4-968f-f2f154277682.png)

I checked that python-config can't be found in python version for windows.

**Comment by petya2164** [comment]
You can try 2 things:
1. Install Python 2.7.9 (it must be the 32-bit version on Windows)
2. Don't use Git Bash - just a regular Command Prompt.

You should also check your VS installation, because your msvc path seems to be incorrect (there should be no folder called "amd64"). Did you install Visual Studio Express 2013 for Windows Desktop?
This should be the correct path to CL.exe:
"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\CL.exe"

**Comment by maxlio** [comment]
I installed Python 2.7.9 and tried using windows cmd but nothing has changed , I have a previous installation of Visual Studio 2013 Ultimate in my machine , should I install the express version if not  how can I change my msvc to the correct path?

**Comment by petya2164** [comment]
We cannot really help you if you are running the Ultimate version :(
You can try to configure like this to force the detection of the 32-bit compiler:
`python waf configure --options=cxx_mkspec=cxx_msvc12_x86`

**Comment by Fuzzyma** [comment]
Sorry for digging out this old issue.
Iam on a windows machine. Python 2.7.11 is installed, so is visual studio.
Still I ran across a similar issue. The difference is, that `waf configure` complains about missing `Python.h`. I know I have these headers because they are located in `D:\Python27\include`. I setup the path variable accordingly to point to `D:\Python27` and `D:\Python27\Scripts`.
It also complains about non-found python-config.
I already sucesfully compiled  kodo on another laptop where no python-config was present, too. Thats why I point in that header-direction.
Thanks for any help!

**Comment by Fuzzyma** [comment]
OK - it was about the wrong python version. I installed python 64bit and now its working...
