### ISSUE TITLE
how to clean the buffer of decoder

### ISSUE THREAD

**Issue by stevelorenz** [steinwurf/kodo-python#70]
Hallo, 

i'am a student and doing a small project using kodo-python. I want to simulate a algorithm for several times to get some statistical data.

````
 encoder = encoder_factory.build()
 recoder = decoder_factory.build()  
 decoder = decoder_factory.build()

 # loop for testing number of times
 for i in range(number):
     # loop for packet transmission test 
     # check if the data is same
     decoder.clean()  # need to clean the data in the buffer for new test round
````

just like the code, I want to clean the old data in the decode buffer for the new test round, otherwise if i use `decode.read_payload()` function, it will give the data including past rounds. I do not find the `clean()` or some function like this in the docs, so I just use `decode.build()` to rebuild the decoder. I don't know if this will occupy more hardware resource or other potential problem. So I want to know if there is a clean function or just use rebuild is ok

Best wishes! Thank you so much.

**Comment by mortenvp** [comment]
Hi Steve,
If I remember correctly the factories are "pooled" which means that they 
will actually recycle old decoders/encoders when building new ones. So 
calling build again and again should be pretty effective (since behind 
the scenes you are basically just re-using the old ones).

Hope that makes sense. If you run into performance problems let us know 
- and we can take a deeper look.

- M

**Comment by mortenvp** [comment]
Will close - feel free to re-open if you have additional questions.
